class VoiceAdapter {
  async transcribeAudio(_audioInput, _options = {}) {
    throw new Error("transcribeAudio is not implemented. Connect your own ASR or multimodal speech provider.");
  }

  async synthesizeSpeech(_text, _options = {}) {
    throw new Error("synthesizeSpeech is not implemented. Connect your own TTS or multimodal speech provider.");
  }
}

function createTextOnlyAdapter() {
  return {
    async transcribeText(text) {
      return {
        text: String(text || ""),
        provider: "text-only",
        confidence: 1
      };
    },
    async synthesizeSpeech(text) {
      return {
        text: String(text || ""),
        provider: "text-only",
        audio: null,
        note: "No audio is generated by the text-only adapter."
      };
    }
  };
}

function requiredVoiceProviderShape() {
  return {
    transcribeAudio: "async function(audioInput, options) -> { text, provider, confidence? }",
    synthesizeSpeech: "async function(text, options) -> { audio_url? | audio_base64? | audio?, provider }"
  };
}

module.exports = {
  VoiceAdapter,
  createTextOnlyAdapter,
  requiredVoiceProviderShape
};
